site_title = "MyArxiv"
limit_days = 7
cache_url = "https://github.com/SinGo01/MyArxiv/cache.json"


[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.SE"
title = "Software Engineering"

[[sources]]
limit = 200
category = "cs.CV"
title = "Computer Vision and Pattern Recognition" 

[[sources]]
limit = 150
category = "cs.HC"
title = "Human-Computer Interaction"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.PL"
title = "Programming Languages"

[[sources]]
limit = 200
category = "cs.OS"
title = "Operating Systems" 

[[sources]]
limit = 150
category = "cs.NI"
title = "Networking and Internet Architecture"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
